'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { BellIcon, CheckIcon, TrashIcon } from '@heroicons/react/24/outline';
import { formatDistanceToNow } from 'date-fns';

export default function NotificationsCenter() {
  const [data, setData] = useState({ notifications: [], unreadCount: 0, pagination: { page: 1, pages: 1 } });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = useCallback(() => { setLoading(true); fetch('/api/notifications?limit=30').then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); }).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  useEffect(load, [load]);
  async function markAll() { await fetch('/api/notifications', { method: 'PATCH' }); load(); }
  async function markOne(id, read = true) { await fetch(`/api/notifications/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ read }) }); load(); }
  async function remove(id) { await fetch(`/api/notifications/${id}`, { method: 'DELETE' }); load(); }
  return <main className="site-shell py-10 sm:py-14"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Activity inbox</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em]">Notifications</h1><p className="mt-2 text-[#627570]">Case updates and city notices in one place.</p></div>{data.unreadCount > 0 && <button onClick={markAll} className="button-secondary"><CheckIcon className="h-4 w-4" />Mark all as read</button>}</div>{error && <div className="mt-6 rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{error}</div>}<section className="surface mt-7 overflow-hidden">{loading ? <div className="space-y-3 p-5">{Array.from({length:6}).map((_,i) => <div key={i} className="h-24 animate-pulse rounded-xl bg-[#f0f3f1]" />)}</div> : data.notifications.length ? <div className="divide-y divide-[#edf0ee]">{data.notifications.map((item) => <article key={item._id} className={`flex gap-4 p-5 sm:p-6 ${item.read ? 'bg-white' : 'bg-[#f1f8f5]'}`}><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${item.read ? 'bg-[#eef2f0] text-[#71827e]' : 'bg-[#dff1eb] text-[#0b6b58]'}`}><BellIcon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-extrabold">{item.title}</h2><p className="mt-1 text-sm leading-6 text-[#627570]">{item.message}</p></div><span className="shrink-0 text-xs font-semibold text-[#81908d]">{formatDistanceToNow(new Date(item.createdAt), { addSuffix: true })}</span></div><div className="mt-4 flex flex-wrap items-center gap-2">{item.relatedReport && <Link href={`/reports/${item.relatedReport._id}`} className="button-secondary py-2 text-xs">Open {item.relatedReport.referenceId || 'report'}</Link>}{!item.read && <button onClick={() => markOne(item._id)} className="button-secondary py-2 text-xs"><CheckIcon className="h-4 w-4" />Mark read</button>}<button onClick={() => remove(item._id)} className="grid h-9 w-9 place-items-center rounded-xl border border-[#dce3df] text-rose-700 hover:bg-rose-50" aria-label="Delete notification"><TrashIcon className="h-4 w-4" /></button></div></div></article>)}</div> : <div className="p-12 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#e8f3ef] text-[#0b6b58]"><BellIcon className="h-7 w-7" /></span><h2 className="mt-4 text-xl font-black">You are all caught up</h2><p className="mt-2 text-[#627570]">New case activity and civic notices will appear here.</p></div>}</section></main>;
}
